filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/app/access.log
    json.keys_under_root: true
    json.add_error_key: true

    fields:
      service: log_gen

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
